name: Publish Release

on:
  push:
    branches: ["master"]

jobs:
  publish-ios:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6
    secrets:
      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}

  publish-android:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6
    with:
       publishTask: publishAndroidReleasePublicationToGitHubPackagesRepository