name: Publish Release

on:
  push:
    branches: ["master"]

env:
  PODSPEC_SSH_KEY_EXISTS: ${{ secrets.PODSPEC_SSH_KEY != ''}}
  MODULE: ${{ inputs.module != '' && format('{0}:',inputs.module) || '' }}

jobs:
  kmmbridgepublish:
    concurrency: "kmmbridgepublish-${{ github.repository }}"
    runs-on: macos-12
    steps:
      - name: Random ID for build branch
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          branch: "build-${{ steps.generate-uuid.outputs.uuid }}"

      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: "build-${{ steps.generate-uuid.outputs.uuid }}"

      - name: Apply SSH Key
        if: ${{ env.PODSPEC_SSH_KEY_EXISTS == 'true' }}
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PODSPEC_SSH_KEY }}

      - uses: extractions/netrc@v1
        with:
          machine: ${{ inputs.netrcMachine }}
          username: ${{ secrets.netrcUsername != '' && secrets.netrcUsername || 'cirunner' }}
          password: ${{ secrets.netrcPassword != '' && secrets.netrcPassword || secrets.GITHUB_TOKEN  }}

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache build tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Build Main
        run: ./gradlew kmmBridgePublish -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=${{ github.repository }}  --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"

      - name: Delete branch
        if: always()
        uses: touchlab/action-delete-branch@v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          branches: "build-${{ steps.generate-uuid.outputs.uuid }}"
