name: Publish Release

on:
  push:
    branches: ["master"]

env:
  PODSPEC_SSH_KEY_EXISTS: ${{ secrets.PODSPEC_SSH_KEY != ''}}
  MODULE: ${{ inputs.module != '' && format('{0}:',inputs.module) || '' }}

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6
    secrets:
      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}