name: Publish Release

on:
  push:
    branches: ["master"]

jobs:
#  publish-ios:
#    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6
#    secrets:
#      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}

  publish-android:
    runs-on: macos-latest
       steps:
          uses: actions/checkout@v3
          - name: set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: 'temurin'

            - name: Setup gradle
              uses: gradle/gradle-build-action@v2

            - name: Publish to Maven
              run: ./gradlew publish
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}